### ISSUE TITLE
Set autocomplete to "off" on dcc.Input doesn't work

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash-core-components#457]
Should be `autoComplete` instead.

https://github.com/plotly/dash-core-components/blob/62e90491c67a79edcfb0bdbdf2f5fa134efd791e/src/components/Input.react.js#L161

https://community.plot.ly/t/how-to-disable-suggestions-on-input-component/18711

**Comment by Lander37** [comment]
Not sure if this is the right place to ask, but will this be fixed in a future release? As it is still broken as of dcc v0.44. Or if there are any workarounds to disable autocomplete for now? Thanks!

**Comment by thinkjrs** [comment]
@T4rk1n I've been using Dash for a while now and it's the right time for me to jump into dev here. 

I am happy to tackle this issue and should have this weekend to dedicate, pending I can get setup with the development environment--the readme setup/build instructions are crashing on my system (I commented on issue #459 seeking to resolve). 

Despite the setup issues, after looking through the linked code and generated .py modules, I'm assuming that other html attributes not camelCased need to be. Specifically:
- autocomplete
- autofocus
- inputmode
- maxlength
- minlength

What's strange is that the CHANGLOG.md indicates these were handled in release 0.37.0:

  [0.37.0] - 2018-11-04
  Fixed
  Some Input props weren't being picked up by React. Changed:
  autocomplete to autoComplete
  autofocus to autoFocus
  inputmode to inputMode
  maxlength to maxLength
  minlength to minLength

After digging into the release commits it looks like the unit test at `/test/unit/Input.test.js` is missing those above, though they were added to the test dataset.  

Going on the limited amount of digging I've done (and normally I'd just implement this and test first), am I safe to assume that the following will solve the issue (assuming all tests pass)?

1. Change the above attribute names to camelCased
2. Add unit tests for the above on the js side -> I'm assuming pytest/R/everything else is generated?

Thanks for the hand-holding through my first contrib :-)

**Comment by tushar-semwal** [comment]
On setting autocomplete to 'off' for dcc.Input is still NOT working. Is this solved?
I am using dash = 0.39.0

**Comment by ned2** [comment]
You're using a rather old version of Dash. Try updating to the latest,
would be the first thing to do.
